### PR TITLE
Update common.sh

### PR DESCRIPTION
**Pull request by chris-str-cst**
Fixed (octal interpretation (leading zero)) in master.sh

### CODE REVIEW

**Comment by chris-str-cst** [comment]
Without that fix I got: [[: 003009: value too great for base (error token is "003009") on master.sh:36+45

**Comment by eliu** [comment]
There's no error on my side. which bash version did you use to run this script? My Mac's bash current version  is `3.2.57`. 

Anyways, your version still works for me unless redhat does not increment their openshift major version greater than 9.

**Comment by chris-str-cst** [comment]
➜  ~ bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

Hmm, what is then the difference. Do you got settings globally which changes this behavior?

**Comment by eliu** [comment]
the same version ... well, what i've found is the differences between `[[` and `[`, check this out:

```bash
eliuhy@rmbp:tmp $ [ "$(version ${OPENSHIFT_RELEASE})" -gt "$(version 3.7)" ]
eliuhy@rmbp:tmp $ [[ "$(version ${OPENSHIFT_RELEASE})" -gt "$(version 3.7)" ]]
bash: [[: 003009: value too great for base (error token is "003009")
eliuhy@rmbp:tmp $
```

And yes, this is can be reproduced. solution will be either yours or replace `[[` with `[`.
I'll choose to apply your patch. thanks for contributions.

**Pull request merged**
